CREATE TABLE IF NOT EXISTS bases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  code VARCHAR(20) NOT NULL UNIQUE,
  region VARCHAR(120) NOT NULL DEFAULT '',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(254) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role VARCHAR(30) NOT NULL CHECK (role IN ('ADMIN', 'BASE_COMMANDER', 'LOGISTICS_OFFICER')),
  base_id BIGINT REFERENCES bases(id) ON DELETE SET NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (role = 'ADMIN' OR base_id IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS equipment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  asset_tag VARCHAR(60) NOT NULL UNIQUE,
  category VARCHAR(80) NOT NULL,
  description TEXT,
  unit VARCHAR(40) NOT NULL DEFAULT 'units',
  opening_balance INTEGER NOT NULL DEFAULT 0 CHECK (opening_balance >= 0),
  base_id BIGINT NOT NULL REFERENCES bases(id) ON DELETE RESTRICT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS purchases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  base_id BIGINT NOT NULL REFERENCES bases(id) ON DELETE RESTRICT,
  equipment_id BIGINT NOT NULL REFERENCES equipment(id) ON DELETE RESTRICT,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(12, 2) CHECK (unit_price >= 0),
  supplier VARCHAR(160),
  reference VARCHAR(120),
  purchase_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  remarks TEXT,
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Existing installations gain this nullable column without inventing prices
-- for purchases that were recorded before pricing was supported.
ALTER TABLE purchases
  ADD COLUMN IF NOT EXISTS unit_price NUMERIC(12, 2) CHECK (unit_price >= 0);

CREATE TABLE IF NOT EXISTS transfers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_base_id BIGINT NOT NULL REFERENCES bases(id) ON DELETE RESTRICT,
  to_base_id BIGINT NOT NULL REFERENCES bases(id) ON DELETE RESTRICT,
  equipment_id BIGINT NOT NULL REFERENCES equipment(id) ON DELETE RESTRICT,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  transfer_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reference_number VARCHAR(120),
  remarks TEXT,
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED' CHECK (status IN ('COMPLETED', 'CANCELLED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (from_base_id <> to_base_id)
);

CREATE TABLE IF NOT EXISTS assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  base_id BIGINT NOT NULL REFERENCES bases(id) ON DELETE RESTRICT,
  equipment_id BIGINT NOT NULL REFERENCES equipment(id) ON DELETE RESTRICT,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  personnel_name VARCHAR(160) NOT NULL,
  personnel_id VARCHAR(80) NOT NULL,
  assigned_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'RETURNED')),
  assigned_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  remarks TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS expenditures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  base_id BIGINT NOT NULL REFERENCES bases(id) ON DELETE RESTRICT,
  equipment_id BIGINT NOT NULL REFERENCES equipment(id) ON DELETE RESTRICT,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  reason TEXT NOT NULL,
  authorized_by VARCHAR(160),
  expenditure_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  remarks TEXT,
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  action VARCHAR(40) NOT NULL,
  module VARCHAR(60) NOT NULL,
  entity_id TEXT,
  base_id BIGINT REFERENCES bases(id) ON DELETE SET NULL,
  old_data JSONB,
  new_data JSONB,
  ip_address VARCHAR(80),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS revoked_tokens (
  jti VARCHAR(100) PRIMARY KEY,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_equipment_base_active ON equipment(base_id, active);
CREATE INDEX IF NOT EXISTS idx_purchases_base_date ON purchases(base_id, purchase_date DESC);
CREATE INDEX IF NOT EXISTS idx_purchases_equipment_base ON purchases(equipment_id, base_id);
CREATE INDEX IF NOT EXISTS idx_transfers_from_date ON transfers(from_base_id, transfer_date DESC);
CREATE INDEX IF NOT EXISTS idx_transfers_to_date ON transfers(to_base_id, transfer_date DESC);
CREATE INDEX IF NOT EXISTS idx_assignments_base_date ON assignments(base_id, assigned_date DESC);
CREATE INDEX IF NOT EXISTS idx_expenditures_base_date ON expenditures(base_id, expenditure_date DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_base_date ON audit_logs(base_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_users_base_role ON users(base_id, role);
